### ISSUE TITLE
Setting multiple tags and a category

### ISSUE THREAD

**Issue by pietchaki** [BiglySoftware/BiglyBT-plugin-rssfeed#7]
I have a bunch of tags and categories. 
In the filters I want set it up so 1 category and up to 3 tags are applied to the torrent.
Tags are inserted with no problem, but category isn't, instead it creates another Tag with same name as the category.

tags and category names are separated by commas in the filter.
eg.: "Category1, Tag01, Tag02"

How can I do this? Or that's not possible?

**Comment by parg** [comment]
what filter are you talking about?

**Comment by pietchaki** [comment]
RSSFeed Scanner > Options tab > Filters > add or edit any filter.
This is what I refer to as the "Filter" before.
There is a "Set Tags/Category" field there.

![image](https://user-images.githubusercontent.com/6844712/142557592-c76d155d-6231-4e25-bd90-fdcd6b52dfab.png)


---
If I understood correctly, when a download is started, it only looks at tags of the "manual" type, it should also look at Categories there.

Adding "TT_DOWNLOAD_CATEGORY" in this file:
https://github.com/BiglySoftware/BiglyBT-plugin-rssfeed/blob/b0bb4f336e2a70db3d63c2dc58d609fef47a674a/org/kmallan/azureus/rssfeed/TorrentDownloader.java#L149

**Comment by parg** [comment]
Categories have existed for a long time. Tags were introduced to supercede categories with the intent of removing categories after a while. Unfortunately this hasn't happen and both now co-exist.

When tags were introduced this plugin was changed so that it would still work with categories for existing users. If a named category existed the categories were used. If the category didn't exist then tags were used.

I suppose I can change it to do what you want.

**Comment by parg** [comment]
Try plugin version 1.8 (should auto-update)

**Comment by pietchaki** [comment]
1.8 solved it!
Thank you very much!
